---
- name: add {{ subdomain }} to reverse proxy.
  ansible.builtin.blockinfile:
    path: /etc/haproxy/haproxy.cfg
    marker: "## {mark} ANSIBLE MANAGED BLOCK: {{ region }}:{{ subdomain }} ##"
    block: |
      backend {{ region }}:{{ subdomain }}
          option forwardfor
          option originalto
          option persist
          server {{ subdomain }} {{ server_address }}
    validate: haproxy -c -V -f %s
    state: "{{ state | default('present') }}"
  delegate_to: "{{ haproxy_host }}"
  loop: "{{ groups['haproxy'] }}"
  loop_control:
    loop_var: haproxy_host
  notify: restart remote haproxy
