[global]
	workgroup = WORKGROUP
	hosts allow = 192.168.15
	keepalive = 300
	deadtime = 10
	guest account = nobody
	socket options = TCP_NODELAY SO_RCVBUF=8192 SO_SNDBUF=8192

[homes]
   comment = Home Directories
   browseable = no
   writable = yes
;   valid users = %S
;   valid users = MYDOMAIN\%S
