apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-system
  namespace: longhorn-system
spec:
  chart:
    spec:
      version: ">=1.0.0"
  # test:
  #   enable: false
  # values:
  #   defaultClassReplicaCount: 1
