apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 60m
  chart:
    spec:
      chart: longhorn
      version: "1.3.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 30m
  # install:
  #   remediation:
  #     retries: 3
  # values:
  #   persistence:
  #     reclaimPolicy: "Retain"
  #   longhornUI:
  #     replicas: 1
