apiVersion: v1
kind: Pod
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  volumes:
    - name: config-storage
      persistentVolumeClaim:
        claimName: jellyfin-pvc-config
  containers:
    - name: jellyfin
      image: jellyfin/jellyfin:latest
      volumeMounts:
        - mountPath: "/config"
          name: config-storage
