---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: jellyfin
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-pvc-config
        - name: jellyfin-data
          persistentVolumeClaim:
            claimName: jellyfin-pvc-data
      containers:
        image: ghcr.io/linuxserver/jellyfin
        imagePullPolicy: Always
        name: jellyfin
        ports:
          - containerPort: 8096
            name: http-tcp
            protocol: TCP
          - containerPort: 8920
            name: https-tcp
            protocol: TCP
          - containerPort: 1900
            name: dlna-udp
            protocol: UDP
          - containerPort: 7359
            name: discovery-udp
            protocol: UDP
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
          - mountPath: /config
            name: jellyfin-config
          - mountPath: /data
            name: jellyfin-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
