---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 5m0s
  url: https://github.com/jellyfin/jellyfin
  ref:
    branch: master
