---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: persistent-longhorn
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

