---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 5m
  url: https://github.com/rook/rook.git
  ref:
    branch: v1.15.0
